---
title: "転職活動を始めました"
date: 2024-01-28 00:34:12 +0900
date-modified: last-modified
categories: [diary]
draft: true
---

こんにちは。i9wa4 です。

今年 (2024年) 1月中旬から転職活動を始めたので今の気持ちを書き残しておきます。

## 1. 転職活動を始めた理由

転職活動に至った理由は以下です。

1. 今の働き方を評価されずモチベーションを維持できない
1. 成長できる環境を選びたい

### 1.1. 今の働き方を評価されずモチベーションを維持できない

私は機械学習基盤での業務経験が社内では一番長くなりました。会社の方針として機械学習基盤を含めた一気通貫のデータ分析ソリューション提供を目指しているので一定の評価を期待していましたが、実際は未経験で入社した当初と2年後の現在で給与は変わらず据え置きです。

というのも会社の歴史的経緯から評価制度が営業マン・リーダー経験豊富な人材優遇なものとなっているためです。技術面での経験蓄積や社内還元は相対的に加点が小さいんですね。これではモチベーション維持が難しいです。

安易に退職したくはなかったので評価制度の問題点を上長や社長に直接伝えてましたが、変える気はないようでした。 ~~せっかくたくさん採用した中堅エンジニアの退職者が増えている最大の要因がこの評価制度だと個人的に思っています。しかも評価制度に迎合した働き方をして昇進したとて昇給幅が小さいです。これでは割に合わないですね。~~

### 1.2. 成長できる環境を選びたい

もう一つの理由としては、成長できる環境を選ぶ重要性を痛感したことです。

vim-jp というエンジニアコミュニティで優秀な方々が日々議論している様子を見て、たまには自分も参加して、という関わりを楽しむようになって2年近く経ちました。たったそれだけで自分の技術力はグンと引き上げられています。やはりエンジニアにとって環境は大事ですね。

これだけ聞くと優秀な人材の多い会社に対するテイカーではないかと勘違いされてしまいそうですが、 **自分のことを良いと思って採用してくれた会社にとっても伸び代が大きい方が嬉しい** のではないでしょうか。

## 2. 今後の予定

人生はあまりにも短いので迷っている場合ではありません。即断即決の精神で、今年 (2024年) 4月からは新しい会社で笑って過ごしたいと思っています。ただ、選考や退職交渉があるので延びるかもしれませんね。
