---
title: "キャリアについてぼんやり考えていたことを時系列順にまとめる"
date: 2024-10-25 23:17:19 +0900
date-modified: last-modified
categories:
  - "diary"
---

こんにちは。uma-chan です。

言ってしまえばポジティブな就職・転職理由を並べるといったところでしょうか。

## 1. 大学入学時

特に何も考えていなかったのですが、自分が生意気すぎる生徒だったことからそんな生徒を受け持ちたくなくて教師だけは絶対にならないぞとは思っていました。

## 2. 就職活動時

本当にぼんやりとIT系業務をやってみたいと思っていました (ただしスキルは大学の授業で少しだけC言語を書けるようになった程度)。

当時業務系システムの求人が多かったのですがどうしても興味がもてず、実際にモノを動かせたり難しいことに挑戦したりとやりがいのありそうな仕事を選んでみました。

## 3. 1回目の転職活動時

大学時代に住んでいた土地に戻りたくて転職することに。

どうせならと経験を積めなかったプログラミングができてモノを動かすこともできる組み込みエンジニアを選びました。

## 4. 2回目の転職活動時

コロナ禍でテレワークを経験し、今後のライフステージを踏まえた上でテレワークに向いている職種に切り替えようと思っていました。

面白そうだったのでデータサイエンティスト求人に応募してみたところ、景気の良い時期だったためか未経験ながら内定を頂きました。

## 5. 3回目の転職活動時

案件都合でアナリティクスエンジニア業務に取り組んでいました。

この頃はデータ基盤についてブラックボックス状態でしたが、純粋に興味もありましたし、かつこのまま自分が偉くなったときにデータ基盤のことも知らないようでは責任をもってデータ業務の指揮ができないだろうなという危機感からデータエンジニアを志すようになりました。

また、この辺りで本格的に vim-jp Slack で東京のエンジニアの空気感・レベル感を知り、エンジニアとしてのレベルや年収を上げていこうという発想が人生で初めて出てきたことも転職を後押ししてくれました。

体感としてはこの辺りでようやく自分はITエンジニアであると思えるようになりました。

## 6. 4回目の転職活動時

これまでの経験から自分の仕事のモチベーションを上げる要因はどうやら以下の4点のようであると理解できました。

1. チームで仕事ができること
1. 自分の仕事が目の前の社員の役に立っていると胸を張って言えること
1. 自分の仕事が会社の売上につながっていると胸を張って言えること
1. できればエンドユーザーの満足度を高める方向の仕事であること

このような自分の特性を踏まえると、今後の先の長い職業人生で自分が充実感をもつには、技術的なエキスパートに向かっていくというより、マネジメントに取り組んだりビジネスサイドに寄せたりしてより抽象度の高い課題解決に向き合う立場を目指した方が良さそうだなと思うようになりました。

そんなことを考えているところに現職と同じデータエンジニアとしてではなくデータサイエンティストとしてお声がけいただいた会社で2024年11月から働くことにしました。

決め手としては上に挙げた要素を全て満足できそう、将来的なキャリア構築の観点でもプラスになりそう、という点以外にも、事業領域が個人的な趣味と合致し会社の売上貢献に本気になれそうと思った点も意外と大きかったです。

## 7. おわりに

これ以上の詳しい話は飲みの場で！笑
