---
title: "Mac 環境構築手順"
date: 2024-06-17 12:21:36 +0900
date-modified: last-modified
categories:
  - "tech"
  - "tech-mac"
---

こんにちは。i9wa4 です。

私の Mac 環境構築手順をまとめておきます。

## 1. dotfiles 導入

cf. <https://github.com/i9wa4/dotfiles>

## 2. システム設定

- バッテリー
    - バッテリーの状態
        - バッテリー充電の最適化
- コントロールセンター
    - Bluetooth
        - メニューバーに表示
    - バッテリー
        - メニューバーに表示 ON
        - 割合 (%) を表示 ON
    - メニューバーのみ
        - 時計
            - 日付を表示 常に
            - 曜日を表示 ON
            - 秒を表示 ON
        - メニューバーを自動的に表示/非表示 しない
- ディスプレイ
    - Night Shift
        - カスタム 5:00-4:59
- デスクトップと Dock
    - Dock
        - 画面上の位置 左
    - デスクトップとステージマネージャー
        - 壁紙をクリックしてデスクトップを表示
            - ステージマネージャー使用時のみ
    - ウィジェット
        - デフォルトの Web ブラウザ
            - Arc
- 通知
    - 通知センター OFF
    - アプリケーションの通知 システム系以外は OFF
- ロック画面
    - 時間設定 30分
- プライバシーとセキュリティ
    - 画面収録とシステムオーディオ録音
        - Slack
        - Web ブラウザ
        - Zoom
- ユーザとグループ
    - 管理者
- キーボード
    - キーボードショートカット
        - 修飾キー
            - 内蔵キーボード
                - Caps Lock -> Control
- マウス
    - ナチュラルなスクロール OFF
- トラックパッド
    - スクロールとズーム
        - ナチュラルなスクロール OFF

## 3. Zsh

- Ctrl-R のコマンド履歴検索が実行できないとき
    - [zshで「control + R」をやってもコマンド履歴検索が実行できない場合の対処方法。 – 和洋風KAI](https://wayohoo.com/article/6922)

## 4. AWS

### 4.1. Okta 経由

- [AWS アカウントにIAM Identity Center ユーザーポータル経由でサインインする方法](https://www.notion.so/AWS-IAM-Identity-Center-a4eda510decb43f6a51c1df902acf84a?pvs=21)

### 4.2. AWS CLI 経由

- [AWS CLIの最新バージョンのインストールまたは更新 - AWS Command Line Interface](https://docs.aws.amazon.com/ja_jp/cli/latest/userguide/getting-started-install.html)
    - これに従って AWS CLI をインストールする
- [自動認証更新で IAM Identity Center AWS CLI トークンプロバイダーの認証情報を使用するようにを設定します - AWS Command Line Interface](https://docs.aws.amazon.com/ja_jp/cli/latest/userguide/sso-configure-profile-token.html)
- ログイン

    ```sh
    aws sso login --profile xxx
    ```

- 動作確認

    ```sh
    aws ec2 describe-instances --profile xxx
    ```

- default profile の設定手順

    ```sh
    AWS_DEFAULT_PROFILE=xxx
    aws ec2 describe-instances
    aws s3 ls
    ```

- `~/.aws/credentials` の設定
    - Access Keys の説明を読む！

## 5. Arc

### 5.1. 検索エンジン設定

- Google 日本語検索
    - `https://www.google.com/search?q=%s`
- Google 英語検索
    - `https://www.google.com/search?q=%s&gl=us&hl=en&gws_rd=cr&pws=0`
- DuckDuckGo 日本語検索
    - `https://duckduckgo.com/?q=%s&kl=jp-jp&kz=-1&kav=1&kaf=1&k1=-1&ia=web`
- DuckDuckGo 英語検索
    - `https://duckduckgo.com/?q=%s&kl=us-en&kz=-1&kav=1&kaf=1&k1=-1&ia=web`

## 6. その他

- Finder
    - 表示
        - パスバーを表示
    - よく使う項目にユーザーホームをドラッグ&ドロップで追加する
- Docker Desktop
    - Settings
        - General
            - [x] Start Docker Desktop when you sign in to your computer
- Rectangle
    - ログイン時に起動 ON

## 7. (おまけ) ショートカット集

| カテゴリ       | ショートカット     | 説明                           |
| ---            | ---                | ---                            |
| ウインドウ操作 | Command + Tab      | アプリケーション切り替え       |
| ウインドウ操作 | Command + @        | 同一アプリケーションの切り替え |
| その他         | Commad  + Q        | Finder 終了                    |
| その他         | Command + Ctrl + Q | ロック                         |
