---
title: "自作 Vim/Neovim プラグイン markdown-number-header.vim の紹介"
date: 2024-01-02 21:47:46 +0900
date-modified: last-modified
categories: [vim, dev]
---

こんにちは。i9wa4 です。

少し前に作った Vim/Neovim プラグインの紹介記事となります。

## 1. プラグイン概要

- <https://github.com/i9wa4/markdown-number-header.vim>
    - Markdown の見出し番号を付ける or 更新するプラグインです。
    - Deno と Denops に依存しています。


## 2. プラグインを作ることになったきっかけ

[Markdown All in One](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one)
という VSCode 拡張の Markdown 見出し番号を付ける機能を Vim でも使いたかったのですが、CLI アプリケーション (Formatter) や Vim プラグインを探しても見つからなかったので自作しようと思い至りました。

## 3. Denops プラグインとして作ろうと思った理由

まず、自分が Vim 上でしか使わないため CLI アプリケーションとしてではなく Vim プラグインとして作ろうとは思ってました。  
そして私は Vim 使いなので Vim script で書くか Denops プラグインとして TypeScript で書くかの二択で、楽しそうなので後者を選びました。

## 4. Denops プラグイン開発体験について

初めて Denops プラグインを作ったし、しかも TypeScript にも触れたことがなかったのですが意外と困ることは少なかったです。  
核となる見出し番号を振る処理は TypeScript の本領発揮という感じで楽に書けましたね。  
まず以下のドキュメントに従ってチュートリアルを終えて、あとは先人の Denops プラグインのリポジトリを覗いてお作法を学びつつプラグインを完成させました。

- 参考ページ:
    - [Deno で Vim/Neovim のプラグインを書く (denops.vim) \| Zenn](https://zenn.dev/lambdalisue/articles/b4a31fba0b1ce95104c9)
    - [Introduction - Denops Documentation](https://vim-denops.github.io/denops-documentation/) (英語版)

## 5. 感想

今も毎日使っているプラグインなので「無いんだったら作ればいい」精神でフッ軽に作れたことを嬉しく思ってます。  
今後も必要なものは自分で作っていたいですね。
